// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Argus.Coordinator.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "service_states",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false),
                    resume_point = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_service_states", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "service_status_reports",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    report_timestamp = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    report_service_name = table.Column<string>(type: "text", nullable: false),
                    report_source = table.Column<string>(type: "text", nullable: false),
                    report_image = table.Column<string>(type: "text", nullable: false),
                    report_status = table.Column<int>(type: "integer", nullable: false),
                    report_message = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_service_status_reports", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_service_states_id",
                table: "service_states",
                column: "id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_service_status_reports_id",
                table: "service_status_reports",
                column: "id",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "service_states");

            migrationBuilder.DropTable(
                name: "service_status_reports");
        }
    }
}
