// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable CS1591

namespace Argus.Coordinator.Migrations
{
    public partial class ConvertStatusReports : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("update ServiceStatusReports set Report_Status = 5 where Report_Status == 3");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("update ServiceStatusReports set Report_Status = 3 where Report_Status == 5");
        }
    }
}
