// <auto-generated/>

using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable CS1591

namespace Argus.Coordinator.Migrations
{
    public partial class DateTimeOffsetToDateTime : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
