// <auto-generated/>

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable CS1591

namespace Argus.Coordinator.Migrations
{
    public partial class StatusReports : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ServiceStatusReports",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Report_Timestamp = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    Report_ServiceName = table.Column<string>(type: "TEXT", nullable: false),
                    Report_Source = table.Column<string>(type: "TEXT", nullable: false),
                    Report_Image = table.Column<string>(type: "TEXT", nullable: false),
                    Report_Status = table.Column<int>(type: "INTEGER", nullable: false),
                    Report_Message = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ServiceStatusReports", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ServiceStatusReports_Id",
                table: "ServiceStatusReports",
                column: "Id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ServiceStatusReports_Report_Image",
                table: "ServiceStatusReports",
                column: "Report_Image");

            migrationBuilder.CreateIndex(
                name: "IX_ServiceStatusReports_Report_ServiceName",
                table: "ServiceStatusReports",
                column: "Report_ServiceName");

            migrationBuilder.CreateIndex(
                name: "IX_ServiceStatusReports_Report_Source",
                table: "ServiceStatusReports",
                column: "Report_Source");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ServiceStatusReports");
        }
    }
}
