// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CS1591

namespace Argus.Coordinator.Migrations
{
    public partial class IndexSourceIdentifiers : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "ix_service_image_sources_source_identifier",
                table: "service_image_sources",
                column: "source_identifier");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_service_image_sources_source_identifier",
                table: "service_image_sources");
        }
    }
}
