// <auto-generated/>

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CS1591

namespace Argus.Coordinator.Migrations
{
    public partial class AddImageSource : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "service_image_sources",
                columns: table => new
                {
                    service_name = table.Column<string>(type: "text", nullable: false),
                    source = table.Column<string>(type: "text", nullable: false),
                    first_visited_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    source_identifier = table.Column<string>(type: "text", nullable: true),
                    revisit_count = table.Column<int>(type: "integer", nullable: false),
                    last_revisited_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_service_image_sources", x => new { x.service_name, x.source });
                });

            migrationBuilder.CreateIndex(
                name: "ix_service_image_sources_first_visited_at",
                table: "service_image_sources",
                column: "first_visited_at");

            migrationBuilder.CreateIndex(
                name: "ix_service_image_sources_last_revisited_at",
                table: "service_image_sources",
                column: "last_revisited_at");

            migrationBuilder.CreateIndex(
                name: "ix_service_image_sources_revisit_count",
                table: "service_image_sources",
                column: "revisit_count");

            migrationBuilder.CreateIndex(
                name: "ix_service_image_sources_service_name_source",
                table: "service_image_sources",
                columns: new[] { "service_name", "source" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "service_image_sources");
        }
    }
}
